CREATE TABLE TestDB.dbo.NOM_CONCEPTOS_NOMINA (
                ID_CONCEPTO INT IDENTITY NOT NULL,
                DESC_CONCEPTO VARCHAR(MAX) NOT NULL,
                COD_CONCEPTO INT NOT NULL,
                CONSTRAINT NOM_CONCEPTOS_NOMINA_pk PRIMARY KEY (ID_CONCEPTO)
)

CREATE TABLE TestDB.dbo.NOM_EMPLEADOS (
                ID_EMPLEADO INT NOT NULL,
                ID_SOLICITUD INT NOT NULL,
                CONSTRAINT NOM_EMPLEADOS_pk PRIMARY KEY (ID_EMPLEADO)
)

CREATE TABLE TestDB.dbo.NOM_NOMINA_DEFINITIVA (
                REGISTRO INT IDENTITY NOT NULL,
                FCH_CRE DATETIME NOT NULL,
                ID_CONCEPTO INT NOT NULL,
                ID_EMPLEADO INT NOT NULL,
                VAL_NOMINA INT NOT NULL,
                CANTIDAD INT NOT NULL,
                CONSTRAINT NOM_NOMINA_DEFINITIVA_pk PRIMARY KEY (REGISTRO)
)

CREATE TABLE TestDB.dbo.REG_SOLICITUDES_INGRESOS (
                ID_SOLICITUD INT IDENTITY NOT NULL,
                DOCUMENTO VARCHAR(50) NOT NULL,
                APELLIDOS VARCHAR(100) NOT NULL,
                NOMBRES VARCHAR(100) NOT NULL,
                CONSTRAINT REG_SOLICITUDES_INGRESOS_pk PRIMARY KEY (ID_SOLICITUD)
)

CREATE TABLE TestDB.dbo.LOG_CONSULTA_NOM_NOMINA_DEFINITIVA (
                ID_REGISTRO INT IDENTITY NOT NULL,
                USUARIO VARCHAR(30),
                FECHA DATETIME,
                OPERACION VARCHAR(10),
                DESCRIPCION_DE_EVENTO VARCHAR(MAX) 
)

ALTER TABLE TestDB.dbo.NOM_NOMINA_DEFINITIVA ADD CONSTRAINT NOM_CONCEPTOS_NOMINA_NOM_NOMINA_DEFINITIVA_fk
FOREIGN KEY (ID_CONCEPTO)
REFERENCES TestDB.dbo.NOM_CONCEPTOS_NOMINA (ID_CONCEPTO)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE TestDB.dbo.NOM_NOMINA_DEFINITIVA ADD CONSTRAINT NOM_EMPLEADOS_NOM_NOMINA_DEFINITIVA_fk
FOREIGN KEY (ID_EMPLEADO)
REFERENCES TestDB.dbo.NOM_EMPLEADOS (ID_EMPLEADO)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE TestDB.dbo.NOM_EMPLEADOS ADD CONSTRAINT REG_SOLICITUDES_INGRESOS_NOM_EMPLEADOS_fk
FOREIGN KEY (ID_SOLICITUD)
REFERENCES TestDB.dbo.REG_SOLICITUDES_INGRESOS (ID_SOLICITUD)
ON DELETE NO ACTION
ON UPDATE NO ACTION

